version: "3"

services:
  busman:
      container_name: business_server
      image: airnh/bases:webdev
      privileged: true
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      volumes:
        - ./BusinessServer/projects:/home/projects
      network_mode: bridge
      ports:
        - "8080:3000" # react app
        - "80:4000"
        - "81:4001"
      links:
        - connlog_mongo
        - ticket_mongo
        - bus_mongo
        - userinfo_mongo
      #entrypoint: ["yarn", "install", "&&" , "yarn", "start"]
      # entrypoint: ["bash", "run.sh"]
  connlog_mongo:
      container_name: connlog_mongo
      image: mongo
      privileged: true
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin
      network_mode: bridge
    
  ticket_mongo:
      container_name: ticket_mongo
      image: mongo
      privileged: true
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin
      network_mode: bridge
      
  bus_mongo:
      container_name: bus_mongo
      image: mongo
      privileged: true
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin
      network_mode: bridge

  userinfo_mongo:
      container_name: userinfo_mongo
      image: mongo
      privileged: true
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin
      network_mode: bridge

