export const DummyBusSchedules = [
  {
    bus_id: "1adfe2",
    total_seats: 25,
    booked_seats: 0,
    travel_duration: 48,
    departure_city: "Vancouver BC",
    departure_date: new Date(2022, 1, 1),
    arrival_city: "Toronto ON",
  },
  {
    bus_id: "2434d2",
    total_seats: 21,
    booked_seats: 3,
    travel_duration: 36,
    departure_city: "Calgary AB",
    departure_date: new Date(2022, 1, 3),
    arrival_city: "Toronto ON",
  },
  {
    bus_id: "6ddf4d2",
    total_seats: 31,
    booked_seats: 30,
    travel_duration: 36,
    departure_city: "Vancouver BC",
    departure_date: new Date(2022, 2, 1),
    arrival_city: "Richmond BC",
  },
  {
    bus_id: "9398d2",
    total_seats: 31,
    booked_seats: 4,
    travel_duration: 55,
    departure_city: "Richmond BC",
    departure_date: new Date(2022, 1, 15),
    arrival_city: "Toronto ON",
  },
  {
    bus_id: "fffee",
    total_seats: 11,
    booked_seats: 6,
    travel_duration: 24,
    departure_city: "Richmond BC",
    departure_date: new Date(2022, 1, 15),
    arrival_city: "Calgary ON",
  },
]
